#include "math/data_types.h"

#define CHIMERA_AUTHOR "Kavawuvi ^v^ & gbMichelle"
#define CHIMERA_MOD "JerryBrick"
#define CHIMERA_BUILD_NUMBER 50
#define CHIMERA_ALPHA_VERSION -582
#define CHIMERA_LUA_INTERPRETER 2.042

#ifdef CHIMERA_ALPHA_VERSION
#define CHIMERA_BUILD_STRING STR(CHIMERA_ALPHA_VERSION)
#else
#define CHIMERA_BUILD_STRING STR(CHIMERA_BUILD_NUMBER)
#endif
